name: Add Labels to Issues on PR Merge
on:
  push:
    branches:
      - main
      - SDEV
      - STEST
      - PDEV
      - PTEST
jobs:
  merge_job:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          add-labels: "deployed: SDEV"
