# This is a basic workflow to help you get started with Actions

name: Stale

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          days-before-pr-stale: 0
